#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer Autoloader...
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

// Bootstrap Laravel and handle the command...
if (file_exists(__DIR__.'/bootstrap/app.php')) {
    $app = require_once __DIR__.'/bootstrap/app.php';
    $status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
    exit($status);
}
